name: Python Windows Setup

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

permissions:
  contents: write
  
jobs:
  build:
    runs-on: windows-latest  # This will use a Windows runner for your workflow

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # You can change this version as needed

    # Step 3: Clean up the virtual environment if it exists, and create a new one
    - name: Create virtual environment
      run: |
        if (Test-Path venv) {
          Remove-Item -Recurse -Force venv  # Delete venv if it exists
        }
        python -m venv venv  # Create a new virtual environment
        .\venv\Scripts\activate  # Activate the virtual environment

    # Step 4: Print directory structure to debug the location of requirements.txt
    - name: List directory structure
      run: |
        echo "Current directory structure:"
        Get-ChildItem -Recurse  # PowerShell command to list files in the directory

    # Step 5: Install dependencies from the manually created requirements.txt
    - name: Install dependencies
      run: |
        .\venv\Scripts\activate  # Activate the virtual environment
        pip install -r requirements.txt  # Directly reference requirements.txt in the root directory

    # Step 6: Generate and update requirements.txt file
    - name: Generate and update requirements.txt
      run: |
        .\venv\Scripts\activate  # Activate the virtual environment
        pip freeze > requirements.txt  # Update the requirements.txt file with the installed packages

    # Step 6: Commit and push the updated requirements.txt file
    - name: Commit and push updated requirements.txt
      run: |
        git config --global user.name d-jllow  # Replace with your GitHub username
        git config --global user.email dos.jllow@gmail.com  # Replace with your email address
        git add $GITHUB_WORKSPACE/requirements.txt  # Stage the updated requirements.txt file
        git commit -m "Update requirements.txt with installed dependencies"  # Commit the change
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main  # Push the change
