name: Python Windows Setup

on:
  push:
    branches:
      - main  # You can change this to your branch name (e.g., master or any other)

jobs:
  build:
    runs-on: windows-latest  # This will use a Windows runner for your workflow

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python 3.9 (or the version of your choice)
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # You can change this version as needed

    # Step 3: Create and activate the virtual environment
    - name: Create virtual environment
      run: |
        python -m venv venv  # Create a virtual environment
        .\venv\Scripts\activate  # Activate the virtual environment

    # Step 4: Install dependencies from the manually created requirements.txt
    - name: Install dependencies
      run: |
        .\venv\Scripts\activate  # Activate the virtual environment
        pip install --upgrade pip  # Ensure pip is up-to-date
        pip install -r $GITHUB_WORKSPACE/requirements.txt  # Install dependencies from the requirements.txt

    # Step 5: Generate and update the requirements.txt file with the installed dependencies
    - name: Generate and update requirements.txt
      run: |
        .\venv\Scripts\activate  # Activate the virtual environment
        pip freeze > $GITHUB_WORKSPACE/requirements.txt  # Update the requirements.txt file with the installed packages

    # Step 6: Commit and push the updated requirements.txt file to the repository
    - name: Commit and push updated requirements.txt
      run: |
        git config --global user.name "Your Name"  # Replace with your GitHub username
        git config --global user.email "youremail@example.com"  # Replace with your email address
        git add $GITHUB_WORKSPACE/requirements.txt  # Stage the updated requirements.txt file
        git commit -m "Update requirements.txt with installed dependencies"  # Commit the change
        git push https://github.com/${{ github.repository }}.git HEAD:main  # Push the change
