name: Python Linux Setup

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest  # Use Linux runner

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Install Python 3.9

    # Step 3: Upgrade pip and install virtualenv
    - name: Upgrade pip and install virtualenv
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install virtualenv

    # Step 4: Create a virtual environment
    - name: Create virtual environment
      run: python3 -m virtualenv venv

    # Step 5: Cache Python dependencies
    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: python-packages-${{ runner.os }}-${{ hashFiles('requirements_pylinux.txt') }}
        restore-keys: |
          python-packages-${{ runner.os }}-

    # Step 6: Install dependencies
    - name: Install Python dependencies
      run: |
        source venv/bin/activate
        pip install --no-cache-dir -r requirements_pylinux.txt

    # Debugging step: Check installed packages
    - name: List installed packages
      run: |
        source venv/bin/activate
        pip list

    # Step 7: Upload the virtual environment as an artifact
    - name: Upload Python virtual environment
      uses: actions/upload-artifact@v4
      with:
        name: python-venv-linux
        path: venv/
