name: Python Linux Setup

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest  # Use Linux runner

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Install Python 3.9

    # Step 3: Install system dependencies (for packages requiring native dependencies)
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev

    # Step 4: Upgrade pip and install virtualenv
    - name: Upgrade pip and install virtualenv
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install virtualenv

    # Step 5: Create a virtual environment
    - name: Create virtual environment
      run: python3 -m virtualenv venv

    # Step 6: Cache Python dependencies
    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: python-packages-${{ runner.os }}-${{ hashFiles('requirements_pylinux.txt') }}
        restore-keys: |
          python-packages-${{ runner.os }}-

    # Step 7: Install dependencies with force reinstall and verbose logging
    - name: Install Python dependencies (Force Install)
      run: |
        venv/bin/python -m pip install --force-reinstall --no-cache-dir -r requirements_pylinux.txt -v

    # Debugging step: Check installed packages
    - name: List installed packages
      run: venv/bin/python -m pip list

    # Debugging step: Show pip logs for troubleshooting
    - name: Show pip debug logs
      run: cat ~/.cache/pip/log/debug.log || echo "No debug log found"

    # Step 8: Upload the virtual environment as an artifact
    - name: Upload Python virtual environment
      uses: actions/upload-artifact@v4
      with:
        name: python-venv-linux
        path: venv/
