name: R Linux Setup

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest  # Use Linux runner

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up R 4.2.3
    - name: Set up R 4.2.3
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.3'  # Install R 4.2.3

    # Step 3: Install system dependencies for R packages
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
        
        # Add Arrow repository for Ubuntu
        sudo wget -qO - https://dlcdn.apache.org/arrow/arrow-apt-repository.key | sudo apt-key add -
        sudo apt-add-repository "deb https://dlcdn.apache.org/arrow/ubuntu/ all main"
        sudo apt-get update
        
        # Now install libarrow-dev
        sudo apt-get install -y libarrow-dev

    # Step 4: Create a library directory for R packages
    - name: Create R package library
      run: mkdir -p r-library

    # Step 5: Cache R packages to speed up future runs
    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: r-library
        key: r-packages-${{ runner.os }}-${{ hashFiles('requirements_rlinux.txt') }}
        restore-keys: |
          r-packages-${{ runner.os }}-

    # Step 6: Install and download required R packages (Parallelized)
    - name: Download R packages (Parallelized)
      run: |
        Rscript -e '
          options(pkgType = "binary");
          install.packages("pak", repos="https://cloud.r-project.org");
          install.packages("future", repos="https://cloud.r-project.org");
          library(future);
          plan(multisession);
          future({
            pak::pkg_install(readLines("requirements_rlinux.txt"), lib="r-library", dependencies=TRUE)
          })'
      
    # Step 7: Upload downloaded R packages as an artifact
    - name: Upload R package library
      uses: actions/upload-artifact@v4
      with:
        name: r-packages-linux
        path: r-library/
